### ISSUE TITLE
rootPaths.flatMap is not a function

### ISSUE THREAD

**Issue by waji-io** [miguelramos/vtx#26]
Hi,

I was trying out the **latest** version of vtx can't get an app build.

```Shell
vtx --v
vtx/0.0.18 darwin-x64 node-v17.7.2
```

```Shell
# XXX at YYYY in ~/Waji-Development/vtx/waj-web [18:55:52]
→ vtx dev --app kgc-web
error when starting dev server:
TypeError: rootPaths.flatMap is not a function
    at Object.config (/Users/XXX/Waji-Development/vtx/waj-web/node_modules/@websublime/vtx-common/dist/common.js:102:81)
    at resolveConfig (/Users/XXX/.config/yarn/global/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:68223:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createServer (/Users/XXX/.config/yarn/global/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66702:20)
    at async viteServer (/Users/XXX/.config/yarn/global/node_modules/@websublime/vtx-cli/dist/cli.js:134:20)
    at async CAC.<anonymous> (/Users/XXX/.config/yarn/global/node_modules/@websublime/vtx-cli/dist/cli.js:224:5)
(base)
```

Any idea what might be wrong?

**Comment by lucascurri** [comment]
I've fixed it changing the line **9** in **vite.config.js**

from: plugins: [vue(), workspacesAlias(**'.'**)]
to: plugins: [vue(), workspacesAlias(**[]**)]

**Comment by miguelramos** [comment]
Sorry mates for the delay, but sometimes notifications where a bit nasty. As @lucascurri refer the workspace alias as two entries one for an array of string and the second arg to some excludes you may need. You can check it here:

https://github.com/miguelramos/vtx/blob/3de0b2fc658f86c8320f3ebee3eee3ef25b0c08a/packages/common/src/plugin.ts#L18
